### ISSUE TITLE
ignore private/protected variables flag?

### ISSUE THREAD

**Issue by hampsterx** [jric/Dumper.py#1]
Hi there, dumper works great on Django Models but they have many protected (_foo) variables that I would rather exclude from the dump.

Would you mind a PR that added a flag to bypass these variables?

Cheers, TiM

**Comment by jric** [comment]
That sounds useful.  Please go ahead and provide the patch.

**Comment by jric** [comment]
Given the age of this issue with no patch, I'm going to guess that there isn't a great demand for this.  Closing for now.
