### ISSUE TITLE
Could we get tags for release?

### ISSUE THREAD

**Issue by mcepl** [jric/Dumper.py#2]
1. I am missing [test.py](test.py) file in the tarball (as a maintainer of openSUSE package, I would love to run the test suite to make at least a minimal level of assurance we are not delivering junk to our customers).
2. So, I am willing to download tarball from GitHub instead of PyPI, because your released tarball is missing those tests.
3. Except there are no tags on GitHub, so I cannot even find particular release.

**Comment by jric** [comment]
Added release 1.2.0.  Let me know if that doesn't solve the problem.

**Comment by mcepl** [comment]
Perfect, thank you.
